<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $file_name
 * @property string $link
 * @property string $partner
 * @property integer $position_id
 * @property integer $order_id
 * @property boolean $published
 * @property BannerPosition $BannerPosition
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method string         getName()           Returns the current record's "name" value
 * @method string         getFileName()       Returns the current record's "file_name" value
 * @method string         getLink()           Returns the current record's "link" value
 * @method string         getPartner()        Returns the current record's "partner" value
 * @method integer        getPositionId()     Returns the current record's "position_id" value
 * @method integer        getOrderId()        Returns the current record's "order_id" value
 * @method boolean        getPublished()      Returns the current record's "published" value
 * @method BannerPosition getBannerPosition() Returns the current record's "BannerPosition" value
 * @method Banner         setId()             Sets the current record's "id" value
 * @method Banner         setName()           Sets the current record's "name" value
 * @method Banner         setFileName()       Sets the current record's "file_name" value
 * @method Banner         setLink()           Sets the current record's "link" value
 * @method Banner         setPartner()        Sets the current record's "partner" value
 * @method Banner         setPositionId()     Sets the current record's "position_id" value
 * @method Banner         setOrderId()        Sets the current record's "order_id" value
 * @method Banner         setPublished()      Sets the current record's "published" value
 * @method Banner         setBannerPosition() Sets the current record's "BannerPosition" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('partner', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BannerPosition', array(
             'local' => 'position_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}