<?php

/**
 * BaseShopProductBonus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property float $min_interval
 * @property float $percent
 * @property float $sale_value
 * @property float $kg_value
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property ShopProduct $ShopProduct
 * 
 * @method integer          getProductId()    Returns the current record's "product_id" value
 * @method float            getMinInterval()  Returns the current record's "min_interval" value
 * @method float            getPercent()      Returns the current record's "percent" value
 * @method float            getSaleValue()    Returns the current record's "sale_value" value
 * @method float            getKgValue()      Returns the current record's "kg_value" value
 * @method timestamp        getStartDate()    Returns the current record's "start_date" value
 * @method timestamp        getEndDate()      Returns the current record's "end_date" value
 * @method ShopProduct      getShopProduct()  Returns the current record's "ShopProduct" value
 * @method ShopProductBonus setProductId()    Sets the current record's "product_id" value
 * @method ShopProductBonus setMinInterval()  Sets the current record's "min_interval" value
 * @method ShopProductBonus setPercent()      Sets the current record's "percent" value
 * @method ShopProductBonus setSaleValue()    Sets the current record's "sale_value" value
 * @method ShopProductBonus setKgValue()      Sets the current record's "kg_value" value
 * @method ShopProductBonus setStartDate()    Sets the current record's "start_date" value
 * @method ShopProductBonus setEndDate()      Sets the current record's "end_date" value
 * @method ShopProductBonus setShopProduct()  Sets the current record's "ShopProduct" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopProductBonus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_product_bonus');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('min_interval', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('percent', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sale_value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('kg_value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}