<?php

/**
 * BaseShopOrderStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $step
 * @property Doctrine_Collection $ShopOrder
 * @property Doctrine_Collection $ShopOrderStatusLogs
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getStep()                Returns the current record's "step" value
 * @method Doctrine_Collection getShopOrder()           Returns the current record's "ShopOrder" collection
 * @method Doctrine_Collection getShopOrderStatusLogs() Returns the current record's "ShopOrderStatusLogs" collection
 * @method ShopOrderStatus     setId()                  Sets the current record's "id" value
 * @method ShopOrderStatus     setName()                Sets the current record's "name" value
 * @method ShopOrderStatus     setDescription()         Sets the current record's "description" value
 * @method ShopOrderStatus     setStep()                Sets the current record's "step" value
 * @method ShopOrderStatus     setShopOrder()           Sets the current record's "ShopOrder" collection
 * @method ShopOrderStatus     setShopOrderStatusLogs() Sets the current record's "ShopOrderStatusLogs" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopOrderStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_order_status');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('step', 'integer', 1, array(
             'type' => 'integer',
             'unique' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShopOrder', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('ShopOrderStatusLog as ShopOrderStatusLogs', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}