<?php

/**
 * BasePollDate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $poll_id
 * @property integer $answer_id
 * @property string $ip_address
 * @property integer $user_id
 * @property Poll $Poll
 * 
 * @method integer  getPollId()     Returns the current record's "poll_id" value
 * @method integer  getAnswerId()   Returns the current record's "answer_id" value
 * @method string   getIpAddress()  Returns the current record's "ip_address" value
 * @method integer  getUserId()     Returns the current record's "user_id" value
 * @method Poll     getPoll()       Returns the current record's "Poll" value
 * @method PollDate setPollId()     Sets the current record's "poll_id" value
 * @method PollDate setAnswerId()   Sets the current record's "answer_id" value
 * @method PollDate setIpAddress()  Sets the current record's "ip_address" value
 * @method PollDate setUserId()     Sets the current record's "user_id" value
 * @method PollDate setPoll()       Sets the current record's "Poll" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollDate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_date');
        $this->hasColumn('poll_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('answer_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ip_address', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Poll', array(
             'local' => 'poll_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}