<?php

/**
 * BaseShopProductSale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $type_id
 * @property float $percent
 * @property float $sale_value
 * @property float $kg_value
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property string $description
 * @property ShopProduct $ShopProduct
 * @property ShopObjectType $ShopObjectType
 * 
 * @method integer         getProductId()      Returns the current record's "product_id" value
 * @method integer         getTypeId()         Returns the current record's "type_id" value
 * @method float           getPercent()        Returns the current record's "percent" value
 * @method float           getSaleValue()      Returns the current record's "sale_value" value
 * @method float           getKgValue()        Returns the current record's "kg_value" value
 * @method timestamp       getStartDate()      Returns the current record's "start_date" value
 * @method timestamp       getEndDate()        Returns the current record's "end_date" value
 * @method string          getDescription()    Returns the current record's "description" value
 * @method ShopProduct     getShopProduct()    Returns the current record's "ShopProduct" value
 * @method ShopObjectType  getShopObjectType() Returns the current record's "ShopObjectType" value
 * @method ShopProductSale setProductId()      Sets the current record's "product_id" value
 * @method ShopProductSale setTypeId()         Sets the current record's "type_id" value
 * @method ShopProductSale setPercent()        Sets the current record's "percent" value
 * @method ShopProductSale setSaleValue()      Sets the current record's "sale_value" value
 * @method ShopProductSale setKgValue()        Sets the current record's "kg_value" value
 * @method ShopProductSale setStartDate()      Sets the current record's "start_date" value
 * @method ShopProductSale setEndDate()        Sets the current record's "end_date" value
 * @method ShopProductSale setDescription()    Sets the current record's "description" value
 * @method ShopProductSale setShopProduct()    Sets the current record's "ShopProduct" value
 * @method ShopProductSale setShopObjectType() Sets the current record's "ShopObjectType" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopProductSale extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_product_sale');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('percent', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sale_value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('kg_value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('ShopObjectType', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}