<?php

/**
 * BaseShopOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property enum $type
 * @property integer $sort_order
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $ShopOptionValue
 * @property Doctrine_Collection $CategoryOptions
 * @property Doctrine_Collection $ShopProductOptionValueConn
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method string              getName()                       Returns the current record's "name" value
 * @method string              getDescription()                Returns the current record's "description" value
 * @method enum                getType()                       Returns the current record's "type" value
 * @method integer             getSortOrder()                  Returns the current record's "sort_order" value
 * @method Doctrine_Collection getCategories()                 Returns the current record's "Categories" collection
 * @method Doctrine_Collection getShopOptionValue()            Returns the current record's "ShopOptionValue" collection
 * @method Doctrine_Collection getCategoryOptions()            Returns the current record's "CategoryOptions" collection
 * @method Doctrine_Collection getShopProductOptionValueConn() Returns the current record's "ShopProductOptionValueConn" collection
 * @method ShopOption          setId()                         Sets the current record's "id" value
 * @method ShopOption          setName()                       Sets the current record's "name" value
 * @method ShopOption          setDescription()                Sets the current record's "description" value
 * @method ShopOption          setType()                       Sets the current record's "type" value
 * @method ShopOption          setSortOrder()                  Sets the current record's "sort_order" value
 * @method ShopOption          setCategories()                 Sets the current record's "Categories" collection
 * @method ShopOption          setShopOptionValue()            Sets the current record's "ShopOptionValue" collection
 * @method ShopOption          setCategoryOptions()            Sets the current record's "CategoryOptions" collection
 * @method ShopOption          setShopProductOptionValueConn() Sets the current record's "ShopProductOptionValueConn" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_option');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'selectbox',
              1 => 'checkbox',
              2 => 'textarea',
              3 => 'input',
             ),
             ));
        $this->hasColumn('sort_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShopCategory as Categories', array(
             'refClass' => 'ShopCategoryOptionConn',
             'local' => 'option_id',
             'foreign' => 'category_id'));

        $this->hasMany('ShopOptionValue', array(
             'local' => 'id',
             'foreign' => 'option_id'));

        $this->hasMany('ShopCategoryOptionConn as CategoryOptions', array(
             'local' => 'id',
             'foreign' => 'option_id'));

        $this->hasMany('ShopProductOptionValueConn', array(
             'local' => 'id',
             'foreign' => 'option_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}