<?php

/**
 * BaseSectionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Sections
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getSections()    Returns the current record's "Sections" collection
 * @method SectionType         setId()          Sets the current record's "id" value
 * @method SectionType         setName()        Sets the current record's "name" value
 * @method SectionType         setDescription() Sets the current record's "description" value
 * @method SectionType         setSections()    Sets the current record's "Sections" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSectionType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('section_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Section as Sections', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}