<?php

/**
 * BaseFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $body
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $ip_address
 * @property boolean $is_read
 * @property integer $user_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getBody()        Returns the current record's "body" value
 * @method string      getName()        Returns the current record's "name" value
 * @method string      getPhone()       Returns the current record's "phone" value
 * @method string      getEmail()       Returns the current record's "email" value
 * @method string      getIpAddress()   Returns the current record's "ip_address" value
 * @method boolean     getIsRead()      Returns the current record's "is_read" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Feedback    setId()          Sets the current record's "id" value
 * @method Feedback    setTitle()       Sets the current record's "title" value
 * @method Feedback    setBody()        Sets the current record's "body" value
 * @method Feedback    setName()        Sets the current record's "name" value
 * @method Feedback    setPhone()       Sets the current record's "phone" value
 * @method Feedback    setEmail()       Sets the current record's "email" value
 * @method Feedback    setIpAddress()   Sets the current record's "ip_address" value
 * @method Feedback    setIsRead()      Sets the current record's "is_read" value
 * @method Feedback    setUserId()      Sets the current record's "user_id" value
 * @method Feedback    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeedback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feedback');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('ip_address', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('is_read', 'boolean', null, array(
             'type' => 'boolean',
             'default' => '0',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}