<?php

/**
 * BaseActivityLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $object_action_conn_id
 * @property integer $object_type_id
 * @property integer $object_id
 * @property string $sentence_html
 * @property sfGuardUser $sfGuardUser
 * @property ObjectActionConn $ObjectActionConn
 * 
 * @method integer          getUserId()                Returns the current record's "user_id" value
 * @method integer          getObjectActionConnId()    Returns the current record's "object_action_conn_id" value
 * @method integer          getObjectTypeId()          Returns the current record's "object_type_id" value
 * @method integer          getObjectId()              Returns the current record's "object_id" value
 * @method string           getSentenceHtml()          Returns the current record's "sentence_html" value
 * @method sfGuardUser      getSfGuardUser()           Returns the current record's "sfGuardUser" value
 * @method ObjectActionConn getObjectActionConn()      Returns the current record's "ObjectActionConn" value
 * @method ActivityLog      setUserId()                Sets the current record's "user_id" value
 * @method ActivityLog      setObjectActionConnId()    Sets the current record's "object_action_conn_id" value
 * @method ActivityLog      setObjectTypeId()          Sets the current record's "object_type_id" value
 * @method ActivityLog      setObjectId()              Sets the current record's "object_id" value
 * @method ActivityLog      setSentenceHtml()          Sets the current record's "sentence_html" value
 * @method ActivityLog      setSfGuardUser()           Sets the current record's "sfGuardUser" value
 * @method ActivityLog      setObjectActionConn()      Sets the current record's "ObjectActionConn" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_log');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('object_action_conn_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('object_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sentence_html', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('ObjectActionConn', array(
             'local' => 'object_action_conn_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}