<?php

/**
 * BaseEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property integer $subscribe
 * @property string $extra
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getEmail()     Returns the current record's "email" value
 * @method integer getSubscribe() Returns the current record's "subscribe" value
 * @method string  getExtra()     Returns the current record's "extra" value
 * @method Email   setId()        Sets the current record's "id" value
 * @method Email   setEmail()     Sets the current record's "email" value
 * @method Email   setSubscribe() Sets the current record's "subscribe" value
 * @method Email   setExtra()     Sets the current record's "extra" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subscribe', 'integer', 4, array(
             'type' => 'integer',
             'default' => '1',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('extra', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}