<?php

/**
 * BaseBasket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $session_id
 * @property integer $user_id
 * @property integer $cart_count
 * @property float $total_price
 * @property sfGuardUser $Customer
 * @property Doctrine_Collection $BasketItems
 * 
 * @method integer             getSessionId()   Returns the current record's "session_id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getCartCount()   Returns the current record's "cart_count" value
 * @method float               getTotalPrice()  Returns the current record's "total_price" value
 * @method sfGuardUser         getCustomer()    Returns the current record's "Customer" value
 * @method Doctrine_Collection getBasketItems() Returns the current record's "BasketItems" collection
 * @method Basket              setSessionId()   Sets the current record's "session_id" value
 * @method Basket              setUserId()      Sets the current record's "user_id" value
 * @method Basket              setCartCount()   Sets the current record's "cart_count" value
 * @method Basket              setTotalPrice()  Sets the current record's "total_price" value
 * @method Basket              setCustomer()    Sets the current record's "Customer" value
 * @method Basket              setBasketItems() Sets the current record's "BasketItems" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBasket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('basket');
        $this->hasColumn('session_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cart_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('total_price', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));


        $this->index('section_id_inx', array(
             'fields' => 
             array(
              0 => 'session_id',
             ),
             ));
        $this->index('user_id_inx', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Customer', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('BasketItem as BasketItems', array(
             'local' => 'id',
             'foreign' => 'basket_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}