<?php

/**
 * BaseShippingZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property float $value
 * @property string $city
 * @property string $zone
 * @property Doctrine_Collection $sfGuardUser
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method float               getValue()       Returns the current record's "value" value
 * @method string              getCity()        Returns the current record's "city" value
 * @method string              getZone()        Returns the current record's "zone" value
 * @method Doctrine_Collection getSfGuardUser() Returns the current record's "sfGuardUser" collection
 * @method ShippingZone        setId()          Sets the current record's "id" value
 * @method ShippingZone        setName()        Sets the current record's "name" value
 * @method ShippingZone        setDescription() Sets the current record's "description" value
 * @method ShippingZone        setValue()       Sets the current record's "value" value
 * @method ShippingZone        setCity()        Sets the current record's "city" value
 * @method ShippingZone        setZone()        Sets the current record's "zone" value
 * @method ShippingZone        setSfGuardUser() Sets the current record's "sfGuardUser" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShippingZone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_zone');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 125, array(
             'type' => 'string',
             'length' => 125,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('zone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'zone_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}