<?php

/**
 * BaseBannerPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $order_id
 * @property Doctrine_Collection $Banner
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getOrderId()     Returns the current record's "order_id" value
 * @method Doctrine_Collection getBanner()      Returns the current record's "Banner" collection
 * @method BannerPosition      setId()          Sets the current record's "id" value
 * @method BannerPosition      setName()        Sets the current record's "name" value
 * @method BannerPosition      setDescription() Sets the current record's "description" value
 * @method BannerPosition      setOrderId()     Sets the current record's "order_id" value
 * @method BannerPosition      setBanner()      Sets the current record's "Banner" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_position');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order_id', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Banner', array(
             'local' => 'id',
             'foreign' => 'position_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}