<?php

/**
 * BaseContentRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rating
 * @property string $title
 * @property string $description
 * @property integer $user_id
 * @property integer $content_id
 * @property sfGuardUser $rateUser
 * @property Content $Content
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getRating()      Returns the current record's "rating" value
 * @method string        getTitle()       Returns the current record's "title" value
 * @method string        getDescription() Returns the current record's "description" value
 * @method integer       getUserId()      Returns the current record's "user_id" value
 * @method integer       getContentId()   Returns the current record's "content_id" value
 * @method sfGuardUser   getRateUser()    Returns the current record's "rateUser" value
 * @method Content       getContent()     Returns the current record's "Content" value
 * @method ContentRating setId()          Sets the current record's "id" value
 * @method ContentRating setRating()      Sets the current record's "rating" value
 * @method ContentRating setTitle()       Sets the current record's "title" value
 * @method ContentRating setDescription() Sets the current record's "description" value
 * @method ContentRating setUserId()      Sets the current record's "user_id" value
 * @method ContentRating setContentId()   Sets the current record's "content_id" value
 * @method ContentRating setRateUser()    Sets the current record's "rateUser" value
 * @method ContentRating setContent()     Sets the current record's "Content" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContentRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_rating');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rating', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as rateUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}