<?php

/**
 * BaseProductStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $value
 * @property timestamp $date_when
 * @property boolean $is_add
 * @property text $description
 * @property integer $order_id
 * @property integer $created_by
 * @property sfGuardUser $CreatedUser
 * @property ShopProduct $ShopProduct
 * @property ShopOrder $ShopOrder
 * 
 * @method integer      getProductId()   Returns the current record's "product_id" value
 * @method integer      getValue()       Returns the current record's "value" value
 * @method timestamp    getDateWhen()    Returns the current record's "date_when" value
 * @method boolean      getIsAdd()       Returns the current record's "is_add" value
 * @method text         getDescription() Returns the current record's "description" value
 * @method integer      getOrderId()     Returns the current record's "order_id" value
 * @method integer      getCreatedBy()   Returns the current record's "created_by" value
 * @method sfGuardUser  getCreatedUser() Returns the current record's "CreatedUser" value
 * @method ShopProduct  getShopProduct() Returns the current record's "ShopProduct" value
 * @method ShopOrder    getShopOrder()   Returns the current record's "ShopOrder" value
 * @method ProductStock setProductId()   Sets the current record's "product_id" value
 * @method ProductStock setValue()       Sets the current record's "value" value
 * @method ProductStock setDateWhen()    Sets the current record's "date_when" value
 * @method ProductStock setIsAdd()       Sets the current record's "is_add" value
 * @method ProductStock setDescription() Sets the current record's "description" value
 * @method ProductStock setOrderId()     Sets the current record's "order_id" value
 * @method ProductStock setCreatedBy()   Sets the current record's "created_by" value
 * @method ProductStock setCreatedUser() Sets the current record's "CreatedUser" value
 * @method ProductStock setShopProduct() Sets the current record's "ShopProduct" value
 * @method ProductStock setShopOrder()   Sets the current record's "ShopOrder" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductStock extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_stock');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('value', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('date_when', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('is_add', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as CreatedUser', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('ShopProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('ShopOrder', array(
             'local' => 'order_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}