<?php

/**
 * BasePollData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $answer
 * @property integer $created_by
 * @property integer $poll_id
 * @property integer $order_id
 * @property integer $vote_count
 * @property boolean $published
 * @property Poll $Poll
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method string   getAnswer()     Returns the current record's "answer" value
 * @method integer  getCreatedBy()  Returns the current record's "created_by" value
 * @method integer  getPollId()     Returns the current record's "poll_id" value
 * @method integer  getOrderId()    Returns the current record's "order_id" value
 * @method integer  getVoteCount()  Returns the current record's "vote_count" value
 * @method boolean  getPublished()  Returns the current record's "published" value
 * @method Poll     getPoll()       Returns the current record's "Poll" value
 * @method PollData setId()         Sets the current record's "id" value
 * @method PollData setAnswer()     Sets the current record's "answer" value
 * @method PollData setCreatedBy()  Sets the current record's "created_by" value
 * @method PollData setPollId()     Sets the current record's "poll_id" value
 * @method PollData setOrderId()    Sets the current record's "order_id" value
 * @method PollData setVoteCount()  Sets the current record's "vote_count" value
 * @method PollData setPublished()  Sets the current record's "published" value
 * @method PollData setPoll()       Sets the current record's "Poll" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_data');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('answer', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('poll_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('vote_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Poll', array(
             'local' => 'poll_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'answer',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}