<?php

/**
 * BaseProdContType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $sort_order
 * @property Doctrine_Collection $ProductToProduct
 * @property Doctrine_Collection $ProductToContent
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method integer             getSortOrder()        Returns the current record's "sort_order" value
 * @method Doctrine_Collection getProductToProduct() Returns the current record's "ProductToProduct" collection
 * @method Doctrine_Collection getProductToContent() Returns the current record's "ProductToContent" collection
 * @method ProdContType        setId()               Sets the current record's "id" value
 * @method ProdContType        setName()             Sets the current record's "name" value
 * @method ProdContType        setDescription()      Sets the current record's "description" value
 * @method ProdContType        setSortOrder()        Sets the current record's "sort_order" value
 * @method ProdContType        setProductToProduct() Sets the current record's "ProductToProduct" collection
 * @method ProdContType        setProductToContent() Sets the current record's "ProductToContent" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProdContType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prod_cont_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sort_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductToProduct', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('ProductToContent', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}