<?php

/**
 * BaseShopProductOptionValueConn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $option_id
 * @property integer $value_id
 * @property integer $quantity
 * @property ShopProduct $Product
 * @property ShopOptionValue $OptionValue
 * @property ShopOption $Option
 * 
 * @method integer                    getProductId()   Returns the current record's "product_id" value
 * @method integer                    getOptionId()    Returns the current record's "option_id" value
 * @method integer                    getValueId()     Returns the current record's "value_id" value
 * @method integer                    getQuantity()    Returns the current record's "quantity" value
 * @method ShopProduct                getProduct()     Returns the current record's "Product" value
 * @method ShopOptionValue            getOptionValue() Returns the current record's "OptionValue" value
 * @method ShopOption                 getOption()      Returns the current record's "Option" value
 * @method ShopProductOptionValueConn setProductId()   Sets the current record's "product_id" value
 * @method ShopProductOptionValueConn setOptionId()    Sets the current record's "option_id" value
 * @method ShopProductOptionValueConn setValueId()     Sets the current record's "value_id" value
 * @method ShopProductOptionValueConn setQuantity()    Sets the current record's "quantity" value
 * @method ShopProductOptionValueConn setProduct()     Sets the current record's "Product" value
 * @method ShopProductOptionValueConn setOptionValue() Sets the current record's "OptionValue" value
 * @method ShopProductOptionValueConn setOption()      Sets the current record's "Option" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopProductOptionValueConn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_product_option_value_conn');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('value_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopProduct as Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ShopOptionValue as OptionValue', array(
             'local' => 'value_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ShopOption as Option', array(
             'local' => 'option_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}