<?php

/**
 * BaseShopObjectType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $object_model_name
 * @property string $object_table_name
 * @property string $name
 * @property string $extra
 * @property Doctrine_Collection $ShopProductSale
 * @property Doctrine_Collection $ShopSale
 * @property Doctrine_Collection $ShopBonus
 * @property Doctrine_Collection $ShopCoupon
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getObjectModelName()   Returns the current record's "object_model_name" value
 * @method string              getObjectTableName()   Returns the current record's "object_table_name" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getExtra()             Returns the current record's "extra" value
 * @method Doctrine_Collection getShopProductSale()   Returns the current record's "ShopProductSale" collection
 * @method Doctrine_Collection getShopSale()          Returns the current record's "ShopSale" collection
 * @method Doctrine_Collection getShopBonus()         Returns the current record's "ShopBonus" collection
 * @method Doctrine_Collection getShopCoupon()        Returns the current record's "ShopCoupon" collection
 * @method ShopObjectType      setId()                Sets the current record's "id" value
 * @method ShopObjectType      setObjectModelName()   Sets the current record's "object_model_name" value
 * @method ShopObjectType      setObjectTableName()   Sets the current record's "object_table_name" value
 * @method ShopObjectType      setName()              Sets the current record's "name" value
 * @method ShopObjectType      setExtra()             Sets the current record's "extra" value
 * @method ShopObjectType      setShopProductSale()   Sets the current record's "ShopProductSale" collection
 * @method ShopObjectType      setShopSale()          Sets the current record's "ShopSale" collection
 * @method ShopObjectType      setShopBonus()         Sets the current record's "ShopBonus" collection
 * @method ShopObjectType      setShopCoupon()        Sets the current record's "ShopCoupon" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopObjectType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_object_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_model_name', 'string', 125, array(
             'type' => 'string',
             'length' => 125,
             ));
        $this->hasColumn('object_table_name', 'string', 125, array(
             'type' => 'string',
             'length' => 125,
             ));
        $this->hasColumn('name', 'string', 125, array(
             'type' => 'string',
             'length' => 125,
             ));
        $this->hasColumn('extra', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShopProductSale', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('ShopSale', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('ShopBonus', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('ShopCoupon', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}