<?php

/**
 * BaseAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property Doctrine_Collection $ObjectTypes
 * @property ObjectActionConn $ObjectActionConn
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getBody()             Returns the current record's "body" value
 * @method Doctrine_Collection getObjectTypes()      Returns the current record's "ObjectTypes" collection
 * @method ObjectActionConn    getObjectActionConn() Returns the current record's "ObjectActionConn" value
 * @method Action              setId()               Sets the current record's "id" value
 * @method Action              setName()             Sets the current record's "name" value
 * @method Action              setBody()             Sets the current record's "body" value
 * @method Action              setObjectTypes()      Sets the current record's "ObjectTypes" collection
 * @method Action              setObjectActionConn() Sets the current record's "ObjectActionConn" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('action');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ObjectType as ObjectTypes', array(
             'refClass' => 'ObjectActionConn',
             'local' => 'action_id',
             'foreign' => 'object_type_id'));

        $this->hasOne('ObjectActionConn', array(
             'local' => 'id',
             'foreign' => 'action_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}