<?php

/**
 * BaseShopOrderStatusLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $order_id
 * @property integer $status_id
 * @property integer $user_id
 * @property timestamp $when_date
 * @property string $description
 * @property ShopOrder $ShopOrder
 * @property ShopOrderStatus $ShopOrderStatus
 * @property sfGuardUser $Customer
 * 
 * @method integer            getOrderId()         Returns the current record's "order_id" value
 * @method integer            getStatusId()        Returns the current record's "status_id" value
 * @method integer            getUserId()          Returns the current record's "user_id" value
 * @method timestamp          getWhenDate()        Returns the current record's "when_date" value
 * @method string             getDescription()     Returns the current record's "description" value
 * @method ShopOrder          getShopOrder()       Returns the current record's "ShopOrder" value
 * @method ShopOrderStatus    getShopOrderStatus() Returns the current record's "ShopOrderStatus" value
 * @method sfGuardUser        getCustomer()        Returns the current record's "Customer" value
 * @method ShopOrderStatusLog setOrderId()         Sets the current record's "order_id" value
 * @method ShopOrderStatusLog setStatusId()        Sets the current record's "status_id" value
 * @method ShopOrderStatusLog setUserId()          Sets the current record's "user_id" value
 * @method ShopOrderStatusLog setWhenDate()        Sets the current record's "when_date" value
 * @method ShopOrderStatusLog setDescription()     Sets the current record's "description" value
 * @method ShopOrderStatusLog setShopOrder()       Sets the current record's "ShopOrder" value
 * @method ShopOrderStatusLog setShopOrderStatus() Sets the current record's "ShopOrderStatus" value
 * @method ShopOrderStatusLog setCustomer()        Sets the current record's "Customer" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopOrderStatusLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_order_status_log');
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('when_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopOrder', array(
             'local' => 'order_id',
             'foreign' => 'id'));

        $this->hasOne('ShopOrderStatus', array(
             'local' => 'status_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Customer', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}