<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $content_id
 * @property string $name
 * @property string $email
 * @property string $comment_text
 * @property integer $created_by
 * @property Content $Content
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method integer getContentId()    Returns the current record's "content_id" value
 * @method string  getName()         Returns the current record's "name" value
 * @method string  getEmail()        Returns the current record's "email" value
 * @method string  getCommentText()  Returns the current record's "comment_text" value
 * @method integer getCreatedBy()    Returns the current record's "created_by" value
 * @method Content getContent()      Returns the current record's "Content" value
 * @method Comment setId()           Sets the current record's "id" value
 * @method Comment setContentId()    Sets the current record's "content_id" value
 * @method Comment setName()         Sets the current record's "name" value
 * @method Comment setEmail()        Sets the current record's "email" value
 * @method Comment setCommentText()  Sets the current record's "comment_text" value
 * @method Comment setCreatedBy()    Sets the current record's "created_by" value
 * @method Comment setContent()      Sets the current record's "Content" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('comment_text', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}