<?php

/**
 * BaseShopProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property string $img_src
 * @property boolean $is_active
 * @property string $caption
 * @property ShopProduct $Product
 * @property Doctrine_Collection $ShopProduct
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getProductId()   Returns the current record's "product_id" value
 * @method string              getImgSrc()      Returns the current record's "img_src" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method string              getCaption()     Returns the current record's "caption" value
 * @method ShopProduct         getProduct()     Returns the current record's "Product" value
 * @method Doctrine_Collection getShopProduct() Returns the current record's "ShopProduct" collection
 * @method ShopProductImage    setId()          Sets the current record's "id" value
 * @method ShopProductImage    setProductId()   Sets the current record's "product_id" value
 * @method ShopProductImage    setImgSrc()      Sets the current record's "img_src" value
 * @method ShopProductImage    setIsActive()    Sets the current record's "is_active" value
 * @method ShopProductImage    setCaption()     Sets the current record's "caption" value
 * @method ShopProductImage    setProduct()     Sets the current record's "Product" value
 * @method ShopProductImage    setShopProduct() Sets the current record's "ShopProduct" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopProductImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_product_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('img_src', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('caption', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopProduct as Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('ShopProduct', array(
             'local' => 'id',
             'foreign' => 'cover_photo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}