<?php

/**
 * BaseProductComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $product_id
 * @property string $comment
 * @property boolean $is_block
 * @property boolean $is_read
 * @property ShopProduct $ShopProduct
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer        getUserId()      Returns the current record's "user_id" value
 * @method integer        getProductId()   Returns the current record's "product_id" value
 * @method string         getComment()     Returns the current record's "comment" value
 * @method boolean        getIsBlock()     Returns the current record's "is_block" value
 * @method boolean        getIsRead()      Returns the current record's "is_read" value
 * @method ShopProduct    getShopProduct() Returns the current record's "ShopProduct" value
 * @method sfGuardUser    getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method ProductComment setUserId()      Sets the current record's "user_id" value
 * @method ProductComment setProductId()   Sets the current record's "product_id" value
 * @method ProductComment setComment()     Sets the current record's "comment" value
 * @method ProductComment setIsBlock()     Sets the current record's "is_block" value
 * @method ProductComment setIsRead()      Sets the current record's "is_read" value
 * @method ProductComment setShopProduct() Sets the current record's "ShopProduct" value
 * @method ProductComment setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_comment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_block', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_read', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}