<?php

/**
 * BaseCategoryContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $category_id
 * @property Content $Content
 * @property Category $Category
 * 
 * @method integer         getContentId()   Returns the current record's "content_id" value
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method Content         getContent()     Returns the current record's "Content" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method CategoryContent setContentId()   Sets the current record's "content_id" value
 * @method CategoryContent setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryContent setContent()     Sets the current record's "Content" value
 * @method CategoryContent setCategory()    Sets the current record's "Category" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_content');
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}