<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $slug
 * @property integer $category_id
 * @property string $image_name
 * @property string $body
 * @property integer $order_id
 * @property Category $Category
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method string   getTitle()       Returns the current record's "title" value
 * @method string   getSlug()        Returns the current record's "slug" value
 * @method integer  getCategoryId()  Returns the current record's "category_id" value
 * @method string   getImageName()   Returns the current record's "image_name" value
 * @method string   getBody()        Returns the current record's "body" value
 * @method integer  getOrderId()     Returns the current record's "order_id" value
 * @method Category getCategory()    Returns the current record's "Category" value
 * @method Page     setId()          Sets the current record's "id" value
 * @method Page     setTitle()       Sets the current record's "title" value
 * @method Page     setSlug()        Sets the current record's "slug" value
 * @method Page     setCategoryId()  Sets the current record's "category_id" value
 * @method Page     setImageName()   Sets the current record's "image_name" value
 * @method Page     setBody()        Sets the current record's "body" value
 * @method Page     setOrderId()     Sets the current record's "order_id" value
 * @method Page     setCategory()    Sets the current record's "Category" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('image_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'body',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}