<?php

/**
 * BaseObjectType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $object_model_name
 * @property string $object_table_name
 * @property string $body
 * @property string $sentence_format
 * @property Doctrine_Collection $Actions
 * @property ObjectActionConn $ObjectActionConn
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getSlug()              Returns the current record's "slug" value
 * @method string              getObjectModelName()   Returns the current record's "object_model_name" value
 * @method string              getObjectTableName()   Returns the current record's "object_table_name" value
 * @method string              getBody()              Returns the current record's "body" value
 * @method string              getSentenceFormat()    Returns the current record's "sentence_format" value
 * @method Doctrine_Collection getActions()           Returns the current record's "Actions" collection
 * @method ObjectActionConn    getObjectActionConn()  Returns the current record's "ObjectActionConn" value
 * @method ObjectType          setId()                Sets the current record's "id" value
 * @method ObjectType          setName()              Sets the current record's "name" value
 * @method ObjectType          setSlug()              Sets the current record's "slug" value
 * @method ObjectType          setObjectModelName()   Sets the current record's "object_model_name" value
 * @method ObjectType          setObjectTableName()   Sets the current record's "object_table_name" value
 * @method ObjectType          setBody()              Sets the current record's "body" value
 * @method ObjectType          setSentenceFormat()    Sets the current record's "sentence_format" value
 * @method ObjectType          setActions()           Sets the current record's "Actions" collection
 * @method ObjectType          setObjectActionConn()  Sets the current record's "ObjectActionConn" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObjectType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('object_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('slug', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('object_model_name', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('object_table_name', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sentence_format', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Action as Actions', array(
             'refClass' => 'ObjectActionConn',
             'local' => 'object_type_id',
             'foreign' => 'action_id'));

        $this->hasOne('ObjectActionConn', array(
             'local' => 'id',
             'foreign' => 'object_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}