<?php

/**
 * BasePoll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $question
 * @property integer $order_id
 * @property integer $position_id
 * @property boolean $published
 * @property integer $frequency
 * @property integer $created_by
 * @property integer $updated_by
 * @property PollPosition $PollPosition
 * @property Doctrine_Collection $PollDatas
 * @property Doctrine_Collection $PollDates
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getQuestion()     Returns the current record's "question" value
 * @method integer             getOrderId()      Returns the current record's "order_id" value
 * @method integer             getPositionId()   Returns the current record's "position_id" value
 * @method boolean             getPublished()    Returns the current record's "published" value
 * @method integer             getFrequency()    Returns the current record's "frequency" value
 * @method integer             getCreatedBy()    Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()    Returns the current record's "updated_by" value
 * @method PollPosition        getPollPosition() Returns the current record's "PollPosition" value
 * @method Doctrine_Collection getPollDatas()    Returns the current record's "PollDatas" collection
 * @method Doctrine_Collection getPollDates()    Returns the current record's "PollDates" collection
 * @method Poll                setId()           Sets the current record's "id" value
 * @method Poll                setQuestion()     Sets the current record's "question" value
 * @method Poll                setOrderId()      Sets the current record's "order_id" value
 * @method Poll                setPositionId()   Sets the current record's "position_id" value
 * @method Poll                setPublished()    Sets the current record's "published" value
 * @method Poll                setFrequency()    Sets the current record's "frequency" value
 * @method Poll                setCreatedBy()    Sets the current record's "created_by" value
 * @method Poll                setUpdatedBy()    Sets the current record's "updated_by" value
 * @method Poll                setPollPosition() Sets the current record's "PollPosition" value
 * @method Poll                setPollDatas()    Sets the current record's "PollDatas" collection
 * @method Poll                setPollDates()    Sets the current record's "PollDates" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePoll extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('question', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('position_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => '1',
             ));
        $this->hasColumn('frequency', 'integer', 4, array(
             'type' => 'integer',
             'default' => '86400',
             'length' => 4,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PollPosition', array(
             'local' => 'position_id',
             'foreign' => 'id'));

        $this->hasMany('PollData as PollDatas', array(
             'local' => 'id',
             'foreign' => 'poll_id'));

        $this->hasMany('PollDate as PollDates', array(
             'local' => 'id',
             'foreign' => 'poll_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'question',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}