<?php

/**
 * BaseShopOptionValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $option_id
 * @property string $name
 * @property string $image_name
 * @property integer $sort_order
 * @property ShopOption $Option
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $ShopProductOptionValueConn
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method integer             getOptionId()                   Returns the current record's "option_id" value
 * @method string              getName()                       Returns the current record's "name" value
 * @method string              getImageName()                  Returns the current record's "image_name" value
 * @method integer             getSortOrder()                  Returns the current record's "sort_order" value
 * @method ShopOption          getOption()                     Returns the current record's "Option" value
 * @method Doctrine_Collection getProducts()                   Returns the current record's "Products" collection
 * @method Doctrine_Collection getShopProductOptionValueConn() Returns the current record's "ShopProductOptionValueConn" collection
 * @method ShopOptionValue     setId()                         Sets the current record's "id" value
 * @method ShopOptionValue     setOptionId()                   Sets the current record's "option_id" value
 * @method ShopOptionValue     setName()                       Sets the current record's "name" value
 * @method ShopOptionValue     setImageName()                  Sets the current record's "image_name" value
 * @method ShopOptionValue     setSortOrder()                  Sets the current record's "sort_order" value
 * @method ShopOptionValue     setOption()                     Sets the current record's "Option" value
 * @method ShopOptionValue     setProducts()                   Sets the current record's "Products" collection
 * @method ShopOptionValue     setShopProductOptionValueConn() Sets the current record's "ShopProductOptionValueConn" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopOptionValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_option_value');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('image_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sort_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopOption as Option', array(
             'local' => 'option_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('ShopProduct as Products', array(
             'refClass' => 'ShopProductOptionValueConn',
             'local' => 'value_id',
             'foreign' => 'product_id'));

        $this->hasMany('ShopProductOptionValueConn', array(
             'local' => 'id',
             'foreign' => 'value_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}