<?php

/**
 * BaseProductToProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $relation_product_id
 * @property string $name
 * @property integer $sort_order
 * @property integer $type_id
 * @property ShopProduct $ProductRelation
 * @property ProdContType $ProdContType
 * 
 * @method integer          getProductId()           Returns the current record's "product_id" value
 * @method integer          getRelationProductId()   Returns the current record's "relation_product_id" value
 * @method string           getName()                Returns the current record's "name" value
 * @method integer          getSortOrder()           Returns the current record's "sort_order" value
 * @method integer          getTypeId()              Returns the current record's "type_id" value
 * @method ShopProduct      getProductRelation()     Returns the current record's "ProductRelation" value
 * @method ProdContType     getProdContType()        Returns the current record's "ProdContType" value
 * @method ProductToProduct setProductId()           Sets the current record's "product_id" value
 * @method ProductToProduct setRelationProductId()   Sets the current record's "relation_product_id" value
 * @method ProductToProduct setName()                Sets the current record's "name" value
 * @method ProductToProduct setSortOrder()           Sets the current record's "sort_order" value
 * @method ProductToProduct setTypeId()              Sets the current record's "type_id" value
 * @method ProductToProduct setProductRelation()     Sets the current record's "ProductRelation" value
 * @method ProductToProduct setProdContType()        Sets the current record's "ProdContType" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductToProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_to_product');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('relation_product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sort_order', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopProduct as ProductRelation', array(
             'local' => 'relation_product_id',
             'foreign' => 'id'));

        $this->hasOne('ProdContType', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}