<?php

/**
 * BasePollPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $symbol
 * @property string $description
 * @property Doctrine_Collection $Polls
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getSymbol()      Returns the current record's "symbol" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getPolls()       Returns the current record's "Polls" collection
 * @method PollPosition        setId()          Sets the current record's "id" value
 * @method PollPosition        setName()        Sets the current record's "name" value
 * @method PollPosition        setSymbol()      Sets the current record's "symbol" value
 * @method PollPosition        setDescription() Sets the current record's "description" value
 * @method PollPosition        setPolls()       Sets the current record's "Polls" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_position');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('symbol', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Poll as Polls', array(
             'local' => 'id',
             'foreign' => 'position_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}