<?php

/**
 * BannerPositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerPositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerPositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannerPosition');
    }
}