<?php

/**
 * Basket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Basket extends BaseBasket
{
    public function hasProduct($product_id)
    {
        $q = BasketItemTable::getInstance()->createQuery()
                ->addWhere('basket_id = ?', $this->getId())
                ->addWhere('product_id = ?', $product_id);
        
        return $q->fetchOne();
    }
    
    public function _update()
    {
        $con = Doctrine_Manager::connection()->getDbh();
        $sql = 'SELECT IFNULL(SUM(quantity),0) as total_quantity, IFNULL(SUM(total_price),0) as total_price FROM `basket_item` WHERE basket_id = '.$this->getId();
        
        $result = $con->query($sql)->fetch();
        
        $this->setCartCount($result['total_quantity']);
        $this->setTotalPrice($result['total_price']);
        $this->save();
    }
}