<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function getCount()
    {
        return Doctrine_Query::create()
                    ->from('Content c')->leftJoin('c.CategoryContent o')
                    ->where('o.category_id = ?', $this->getId())
                    ->count();
    }
    public function getContentsWithOrder($limit = 0, $order = array(), $content_id = 0)
    {
        $q = Doctrine_Query::create()
                    ->from('Content c')->leftJoin('c.CategoryContent o')
                    ->where('o.category_id = ?', $this->getId())
                    ->addWhere('c.published =?', 1);
        
        if($content_id)
            $q->addWhere('c.id != ?', $content_id);
        
        if (count($order)){
            $q->orderBy(implode(', ', $order));
        }else{
            $q->orderBy('created_at Desc');
        }
        
        if($limit)
            $q->limit($limit);

        return $q->execute();
    }
    public function getOneContent()
    {
        $q = Doctrine_Query::create()
                ->from('Content c')->leftJoin('c.CategoryContent o')
                ->where('o.category_id = ?', $this->getId())
                ->orderBy('created_at DESC');
                  
        return $q->fetchOne();
    }
    
    public function isMenu()
    {
        foreach(CategoryTable::getMenuCategoriesId() as $cat_id)
            if($cat_id == $this->getId())
                return true;
        
        return false;
    }
    
    public function getActiveContent($limit = 0)
    {
        $q = Doctrine_Query::create()
               ->from('Content c')->leftJoin('c.CategoryContent o')
                ->where('o.category_id =?', $this->getId())
                ->addWhere('c.published =?', 1)
                ->orderBy('created_at ASC');
        return $q->execute();
    }
    
    public function hasContentSlide()
    {
        $q = Doctrine_Query::create()
               ->from('Content c')->leftJoin('c.CategoryContent o')
                ->leftJoin('c.CategoryContent cc')
                ->addWhere('o.category_id = ?', $this->getId())
                ->addWhere('cc.category_id = ?', CategoryTable::TOP_SLIDE)
                ->orderBy('created_at DESC');

        if($q->count())
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    public function getContentSlide()
    {
        $q = Doctrine_Query::create()
               ->from('Content c')->leftJoin('c.CategoryContent o')
                ->leftJoin('c.CategoryContent cc')
                ->addWhere('o.category_id = ?', $this->getId())
                ->addWhere('cc.category_id = ?', CategoryTable::TOP_SLIDE)
                ->orderBy('created_at DESC');

       return $q->fetchOne();
    }
    
}