<?php

/**
 * ContentRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContentRating extends BaseContentRating
{
    public function getContentLink($path = null)
    {
        $path = '/backend.php/content/edit?id='.$this->content_id;
        return '<a href="'.$path.'">'.$this->getContent().'</a>';
    }

}