<?php

/**
 * Poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Poll extends BasePoll
{
    public function getPollDatas()
    {
            $q = Doctrine_Query::create()
                                    ->from('PollData a')
                                    ->where('a.poll_id =?',$this->getId());

            return $q->execute();
    }
    public function getPollDatasOrder($type)
    {
        $q = Doctrine_Query::create()
                    ->from('PollData a')
                    ->where('a.poll_id = ?', $this->getId())
                    ->orderBy('a.order_id '.$type);
        return $q->execute();
    }
    public function getTotalVote()
    {
        $q = Doctrine_Query::create()
                    ->from('PollDate a')
                    ->where('a.poll_id =?', $this->getId());
        
        return $q->count();
    }
}