<?php

/**
 * ProductStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductStock extends BaseProductStock
{
    public function save(Doctrine_Connection $conn = null)
    {
        $this->created_by = sfContext::getInstance()->getUser()->getGuardUser()->getId();
        if($this->value > 0){
            $this->is_add = 1;
        }else{
            $this->is_add = 0;
        }

        parent::save($conn);
        
        $product = $this->getShopProduct();
        $product->updateStock();
    }
}