<?php

/**
 * ShopCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopCategory extends BaseShopCategory
{
    public function renderBreadcrumb($url = 'javascript:void()', $has_id = false)
    {
        $curr = $this;
        $return_html = '<li class="active">'.$this.'</li></ul>'; $i = 0;
        
        $url = $url.( ($has_id)?'?id='.$curr->getId():'' );
        
        while(strlen($curr->getParent()) > 0 && $i < 10){
            $i++;
            $curr = $curr->getParent();
            $return_html = '<li><a href="'.$url.'">'.$curr.'</a> <span class="divider">/</span></li> '.$return_html;
        }
        
        $return_html = '<ul class="breadcrumb">'.$return_html;
        return $return_html;
    }
    
    public function getProducts($limit = 4, $order_by = array())
    {
        $q = ShopProductTable::getInstance()->createQuery();
        $q->addWhere('category_id = ?', $this->getId());
        
        if(count($order_by) > 0){
            $q->orderBy(implode(', ', $order_by));
        }
        
        if($limit)
            $q->limit($limit);
        
        return $q->execute();
    }
}
