<?php

/**
 * ShopProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopProductImage extends BaseShopProductImage
{
    public function delete(Doctrine_Connection $conn = null){
        
        foreach( sfConfig::get('app_product_photo_sizes') as $size ){
            $file_path = sfConfig::get('sf_upload_dir').'/products/'.$size.'/'.$this->getImgSrc();
            if(file_exists($file_path)){
                unlink($file_path);
            }
        }
        
        parent::delete($conn);
    }
}
