<?php

/**
 * ShopOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOption extends BaseShopOption
{
    public function getValuesByProduct($product_id = 0)
    {
        $ids = SmProductOptionValueConnTable::getValueIdsByProduct($product_id);
        
        $q = SmOptionValueTable::getInstance()->createQuery();
        $q->addWhere('option_id = ?', $this->getId());
        if(count($ids) > 0)
            $q->whereIn('id', $ids);
        else{
            $q->addWhere('id = 0');
        }
        
        return $q->execute();
    }
    public function getTextArea()
    {
    }
}
