<?php

/**
 * ShopProductBonusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopProductBonusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopProductBonusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopProductBonus');
    }
}