<?php

/**
 * ShopOrderItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOrderItem extends BaseShopOrderItem
{
    public function setBasketItem($item, $order_id)
    {
        $this->order_id = $order_id;
        $this->quantity = $item->quantity;
        $this->product_id = $item->product_id;
        $this->unit_price = $item->unit_price;
        $this->total_price = $item->total_price;
    }
}