<?php

/**
 * ShopOrderStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOrderStatus extends BaseShopOrderStatus
{
    public function getLatestOrder($limit = 10){
        $q = ShopOrderTable::getInstance()->createQuery()->where('status_id = ?', $this->id)->orderBy('updated_at DESC')->limit($limit);
        
        return $q->execute();
    }
}