<?php

/**
 * ShopOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOrder extends BaseShopOrder
{
    public function updateTransaction()
    {
        $total = ShopOrderTransactionTable::getInstance()->getTotalAmount($this->id);
        
        $this->remain_amount = $this->total_amount - $total;
        $this->save();
    }
    
    public function save(Doctrine_Connection $conn = null)
    {
		/*  
		* $this->getModified(true); 
		функц нь 
		*/
        $modified = $this->getModified(true);
        //die($modified['status_id'] .' => '.$this->status_id);

        if(ShopOrderStatusTable::ADMIN_CONFIRM == $this->status_id && isset($modified['status_id']) ){

            if($modified['status_id'] < $this->status_id){
                if($this->checkProductsInStock()){
                    foreach($this->getOrderItems() as $item){
                        $product = $item->getShopProduct();

                        $product->hasaltStock($item);
                    }
                }else{
                    sfContext::getInstance()->getUser()->setFlash('error', 'Агуулах дахь бараа хүрэлцэхгүй байна');
                    return false;
                }
            }
        }

        if(isset($modified['shipping_fee']) || isset($modified['product_total_amount'])){
            $this->total_amount = $this->product_total_amount + $this->shipping_fee;
            $total = ShopOrderTransactionTable::getInstance()->getTotalAmount($this->id);

            $this->remain_amount = $this->total_amount - $total;
        }
        
        parent::save($conn);
    }
    
    public function checkProductsInStock()
    {
        foreach($this->getOrderItems() as $item ){
            $product = $item->getShopProduct();
            
            if(!$product->hasStock($item->quantity)){
                return false;
            }
        }
        
        return true;
    }
}