<?php

/**
 * ShopOrderTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CMS
 * @subpackage model
 * @author     Lkhagva-Ochir Narmandakh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOrderTransaction extends BaseShopOrderTransaction
{
    public function getGuardUser(){
        return sfGuardUserTable::getInstance()->find($this->user_id);
    }

    public function getStatus()
    {
        return ShopOrderStatusTable::getInstance()->find($this->status_id);
    }
}