<?php

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $is_active
 * @property integer $category_id
 * @property integer $section_id
 * @property Category $Category
 * @property Section $Section
 * @property Doctrine_Collection $Photos
 * @property Doctrine_Collection $Contents
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method integer             getCategoryId()  Returns the current record's "category_id" value
 * @method integer             getSectionId()   Returns the current record's "section_id" value
 * @method Category            getCategory()    Returns the current record's "Category" value
 * @method Section             getSection()     Returns the current record's "Section" value
 * @method Doctrine_Collection getPhotos()      Returns the current record's "Photos" collection
 * @method Doctrine_Collection getContents()    Returns the current record's "Contents" collection
 * @method Gallery             setTitle()       Sets the current record's "title" value
 * @method Gallery             setDescription() Sets the current record's "description" value
 * @method Gallery             setIsActive()    Sets the current record's "is_active" value
 * @method Gallery             setCategoryId()  Sets the current record's "category_id" value
 * @method Gallery             setSectionId()   Sets the current record's "section_id" value
 * @method Gallery             setCategory()    Sets the current record's "Category" value
 * @method Gallery             setSection()     Sets the current record's "Section" value
 * @method Gallery             setPhotos()      Sets the current record's "Photos" collection
 * @method Gallery             setContents()    Sets the current record's "Contents" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('section_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Photos', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $this->hasMany('Content as Contents', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}