<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/13 05:51:34
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_sfMultipleAjaxUploadGalleryPlugin_thumbnails_sizes' => array (
  0 => 50,
  1 => 150,
  2 => 300,
  3 => 450,
),
  'app_sfMultipleAjaxUploadGalleryPlugin_default_size' => 50,
  'app_sfMultipleAjaxUploadGalleryPlugin_portfolio_thumbnails_size' => 150,
  'app_sfMultipleAjaxUploadGalleryPlugin_onDelete' => 'cascade',
  'app_sfMultipleAjaxUploadGalleryPlugin_path_gallery' => 'C:\\myprojects\\github\\lamp\\web\\uploads/gallery/',
  'app_sfMultipleAjaxUploadGalleryPlugin_theme' => 'bootstrap',
  'app_sfMultipleAjaxUploadGalleryPlugin_csstheme' => 'black',
  'app_sfMultipleAjaxUploadGalleryPlugin_defaultPicture' => '/sfMultipleAjaxUploadGalleryPlugin/images/default_picture.png',
  'app_sfMultipleAjaxUploadGalleryPlugin_path_filigrane' => 'C:\\myprojects\\github\\lamp\\web\\uploads/filigrane.png',
  'app_sfMultipleAjaxUploadGalleryPlugin_ratio' => array (
  'enable' => true,
  'value' => 1.5,
),
  'app_sfMultipleAjaxUploadGalleryPlugin_pager_max' => 4,
  'app_sfMultipleAjaxUploadGalleryPlugin_dimensions' => array (
  'min' => 
  array (
    'width' => 0,
    'height' => 0,
  ),
  'max' => 
  array (
    'width' => 615,
    'height' => 400,
  ),
),
  'app_product_photo_sizes' => array (
  0 => 50,
  1 => 150,
  2 => 200,
  3 => 350,
  4 => 480,
  5 => 600,
),
  'app_content_photo_sizes' => array (
  0 => 100,
  1 => 300,
),
  'app_product_list_perpage' => 20,
  'app_shop_order_perpage' => 20,
  'app_ckeditor_basePath' => '/js/ckeditor/',
  'app_ckfinder_basePath' => '/js/ckfinder/',
  'app_domain' => 'http://freshfruits.mn',
));
