<?php
// auto-generated by sfViewConfigHandler
// date: 2014/05/14 08:55:57
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Удирдлагын хэсэг', false, false);

  $response->addStylesheet('/backend/assets/css/bootstrap.min.css', '', array ());
  $response->addStylesheet('/backend/assets/css/bootstrap-responsive.min.css', '', array ());
  $response->addStylesheet('/backend/assets/css/font-awesome.min.css', '', array ());
  $response->addStylesheet('/backend/assets/css/ace-fonts.css', '', array ());
  $response->addStylesheet('/backend/assets/css/ace.min.css', '', array ());
  $response->addStylesheet('/backend/assets/css/ace-responsive.min.css', '', array ());
  $response->addStylesheet('/backend/assets/css/ace-skins.min.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('ckeditor/ckeditor.js', '', array ());
  $response->addJavascript('ckfinder/ckfinder.js', '', array ());
  $response->addJavascript('jquery.form.js', '', array ());
  $response->addJavascript('/backend/assets/js/ace-extra.min.js', '', array ());
  $response->addJavascript('/backend/assets/js/bootstrap.min.js', '', array ());
  $response->addJavascript('/backend/assets/js/ace-elements.min.js', '', array ());
  $response->addJavascript('/backend/assets/js/ace.min.js', '', array ());


