<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    public function setEmailAddress($val) {
        if($this->isNew()){
            $this->_set('username', $val);
        }
        
        return $this->_set('email_address', $val);
    }
    
    public function __toString()
    {
        return $this->getFirstName().' ('.$this->getEmailAddress().' - '.$this->getPhone().')';
    }

    public function profileComplete()
    {
        if(strlen($this->address) > 5 && strlen($this->phone) > 0 && strlen($this->phone2) > 0 ){
            return true;
        }else{
            return false;
        }
    }
}