generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Feedback
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          feedback
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        label : Үйлдэл
        _new:            { label: "Шинээр үүсгэх" }
        _delete:         { label: "Устгах" }
        _edit:           { label: "Засах" }
        _save:           { label: "Хадгалах" }
        _save_and_add:   { label: "Хадгалах, нэмэх" }
        _list:           { label: "Жагсаалт руу буцах" }

      fields:
        name:            { label: Нэр }
        phone:           { label: Утас }
        email:           { label: И-мэйл }
        title:           { label: Гарчиг }
        body:            { label: Текст }
      list:
        title:   Хүсэлтийн Жагсаалт 
        display: [name, description]

      filter:
        display: [name]
      form:   ~
      edit:
        title: Хүсэлт засварлах хэсэг
      new:
        title: Шинэ Хүсэлт үүсгэх

