<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/05/08 21:37:43
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'backend',
      ),
    ),
  ),
);
