<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/09 00:20:39
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
