<?php

/**
 * PluginsfGuardLoginHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardLoginHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardLoginHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardLoginHistory');
    }
}