generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ShopOptionValue
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          shop_option_value
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        label : Үйлдэл
        _new:            { label: "Шинээр үүсгэх" }
        _delete:         { label: "Устгах" }
        _edit:           { label: "Засах" }
        _save:           { label: "Хадгалах" }
        _save_and_add:   { label: "Хадгалах, нэмэх" }
        _list:           { label: "Жагсаалт руу буцах" }
      fields:
        name:            { label: "Нэр" }
        option_id:       { label: Option }
        Option:          { label: Option }
        image_name:      { label: "Зургийн нэр" }
        sort_order:      { label: "Дэс дугаар" }
      list:
        title: Жагсаалт
        display: [name, Option]

      filter:
        display: [ option_id]
      form:
        display:
          Хэл:           [ mn, en ]
          Тохиргоо:      [ option_id, image_name ]
      edit:
        title: "\"Option-ийн утга\" засварлах хэсэг"
      new:
        title: "Шинэ \"option-ийн утга\" үүсгэх"

